### PR TITLE
support geo.{intersects, distance, length}

### PR DESCRIPTION
**Pull request by srepmub**
updated query parsing for geo.* functions, and added django backend implementation.

-add GEOGRAPHY token and Geography AST node
-account for identifier namespace in various places 
-add django implementation using django.contrib.gis 
-use '__' for namespace separator in backend function names 
-fix geo.distance number of args

### CODE REVIEW

**Comment by OliverHofkens** [comment]
Hey, thanks for this, it's looking great! 👍 

Two things I'd like to add (or see added) are:
- Being able to still run the project without having the GIS libraries installed. Currently this crashes on import of the `django.contrib.gis` package.
- Some tests on these features. Although that might be hard if they depend on databases with GIS support. Something to think about.

I'd happily work on those. It would be a good opportunity for me to learn some Geo/GIS stuff!

**Comment by OliverHofkens** [comment]
Just for traceability mentioning that this implements #48

**Comment by OliverHofkens** [comment]
Hey, great work so far! 

I finally found some time to work a bit on this again.
I managed to get some end-to-end integration tests working on this branch: https://github.com/gorilla-co/odata-query/tree/tests/geo-integration-tests

Still ironing out some minor issues. E.g. certain Python versions fail to find the GDAL libraries, while others work fine.

**Comment by svniemeijer** [comment]
Any news on this? I had a look at the failed test and it looked like a linting error (which should probably be easy to resolve).
It would be great if this feature could get integrated.

**Comment by OliverHofkens** [comment]
Hey, sorry about the wait! I've been experimenting with some end-to-end integration tests using a local Spatialite database on this branch: https://github.com/gorilla-co/odata-query/tree/tests/geo-integration-tests 

That's turning out to be a bit of a pain, some versions of Python seem to have issues finding/using the geo libraries. Afterwards I'd still have to get that set up in the Github actions workflows.
If you need this urgently, I'd be willing to merge this as-is and release it under a pre-release tag.

Sorry again, and thanks for your patience 🙏

**Comment by OliverHofkens** [comment]
Bingo, we now have E2E integration tests using a Spatialite database running in Github Actions.
Locally they should be automatically skipped if the required system libraries cannot be loaded 👍 

Adding some colleagues as reviewers for a quick final checkoff and then I'll merge. Thanks again for this!

**Review by OliverHofkens — APPROVED** [review]

**Review by gorilla-seb — APPROVED** [review]

**Pull request merged**
